---
title: "Data loading"
output: html_document
date: "2025-10-28"
---

```{r}
#install.packages("pacman")
library(pacman)
p_load(haven,
       here,
       stargazer,
       summarytools,
       readxl,
       dplyr,
       lubridate,
       ggplot2,
       summarytools,
       devtools,
       zoo,
       tidyverse,
       dataverse,
       devtools,
       WDI,
       wbwdi,
       readxl,
       wid)
```

## Inequality data

```{r The Standardized World Income Inequality Database}
# Direct download using file URL
url <- "https://dataverse.harvard.edu/api/access/datafile/11667866?version=14.0"
temp_dir <- tempdir()
zip_path <- file.path(temp_dir, "swiid9_9.zip")

download.file(url, destfile = zip_path, mode = "wb")

# Unzip all contents
unzip(zip_path, exdir = temp_dir)

# Listing the extracted files
list.files(temp_dir)

# After unzipping
list.files(temp_dir, recursive = TRUE)
rda_file <- file.path(temp_dir, "swiid9_9", "swiid9_9.rda")  

# Loading both files: swiid_summary for visualization and swiid for regressions and capturing obejct names
obj_names <- load(rda_file)
```

Add which indicators we will need:

```{r World Inequality Database}
# https://github.com/world-inequality-database/wid-r-tool
devtools::install_github("world-inequality-database/wid-r-tool")

latam_codes2 <- c("AR", "BO","BR", "CL", "CO", "CR", "CU", "DO", "EC","SV", "GT", "HN", "MX", "NI", "PA", "PY", "PE", "UY", "VE")

data_wid_long <- download_wid(
  indicators = c("shweal", "ahweal","sptinc", "aptinc"), # Shares of personal wealth
  areas = latam_codes2,
  years = 1960:2019,
  perc = c("p99p100", "p0p50") #Top 1% and bottom 50% percentiles
)
# "shweal": Share of net personal wealth
# "ahweal": Average net personal wealth
# "sptinc": Share of pre-tax national income
# "aptinc": Average pre-tax national income

head(data_wid_long)
#Already comes in long format 
```

## Macroeconomic Indicators

```{r World Bank: WDI}
WDIsearch('gdp growth') #NY.GDP.MKTP.KD.ZG - GDP growth (annual %)
WDIsearch('inflation') #NY.GDP.DEFL.KD.ZG - Inflation, GDP deflator (annual %)
WDIsearch('trade') #NE.TRD.GNFS.ZS - Trade (% of GDP)
WDIsearch('unemployment') #JI.UEM.1564.ZS - Unemployment rate, aged 15-64, total (% of total labor force in working age)
WDIsearch("fiscal") #GC.BAL.CASH.CD - Fiscal balance, cash surplus/deficit (current US$)
WDIsearch("Central government debt") #GC.DOD.TOTL.GD.ZS - Central government debt, total (% of GDP)
WDIsearch("school enrollment") #"SE.SEC.ENRR" - School enrollment, secondary (% gross)
#"NY.GDP.PCAP.KD" - GDP per capita

data_wdi <- WDI(latam_codes2,
                c("NY.GDP.MKTP.KD.ZG",
                  "NY.GDP.DEFL.KD.ZG", 
                  "NE.TRD.GNFS.ZS", 
                  "JI.UEM.1564.ZS",
                  "GC.DOD.TOTL.GD.ZS",
                  "SE.SEC.ENRR",
                  "NY.GDP.PCAP.KD"),
                start = 1960,
                end = 2019)
```

## Financial Crises Indicators

```{r Comprehensive typology: Nguyen et al.}
# Had to save locally and load data to github :(((((
crises_df <- read_excel("Data/FinancialCrises_Nguyen.xlsx")
```
